config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'
  resources :favorites, only: [:create, :destroy]
  get '/users/:id/favorites', to: 'users#favorites'
  resources :feeds
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :pictures do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  validates :title, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :favorites, dependent: :destroy
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのPictureをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのPictureをお気に入り解除しました"
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  def index
    @feeds = Feed.all
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end
  def feed_params
    params.require(:feed).permit(:image, :image_cache)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  #アクションが実行される前に、以下のメソッドを実行する。onlyオプションを使用し、指定されたアクションが実行された場合のみbefore_actionが実行される。
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}
  #indexビューの呼び出し
  def index
    @pictures = Picture.all.order(created_at: :desc)
  end
  #pictureのインスタンスが一つ入っている変数を、ビューに渡す。新しいpictureの作成。newメソッドはインスタンスのみの生成で、レコードをテーブルに保存しない。
  def new
    @picture = Picture.new
  end
  #createメソッドを使用することで、テーブルにレコードを作成、保存できる。
  def create
    #フォームに記述した内容を送信した場合、parametersという名のハッシュ値に変換して、アプリ内部に送り込む。
    @picture = current_user.pictures.build(picture_params)
    #戻るボタンが実行されたら、
    if params[:back]
      #入力フォームを再描写する。renderメソッドを使用することで、createアクションで呼び出すviewをnew.html.erbに変換できる。
      render :new
    else
      #newメソッドで作成したインスタンスをsaveメソッドを使用し、テーブルに保存する。
      if @picture.save
        #picture投稿時にユーザー宛にメールが送信される。
        PictureMailer.picture_mail(@picture).deliver
        #pictures_pathというPrefixを書くことで、"/pictures"というURLの指定をする。一覧画面へ遷移して、"Pictureを作成しました！"とメッセージを表示する。
        redirect_to pictures_path, notice: "Pictureを作成しました！"
      else
        render :new
      end
    end
  end
  #現在ログインしているユーザのお気に入りのpicture_idを取得し、そのデータをfavoriteインスタンス変数に格納。
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    @user = @picture.user
  end
  #編集
  def edit
  end
  #編集された内容で、データを更新する。
  def update
    #送られてきた内容を、paramsメソッドで取得。引数の値で更新できる。
    if @picture.update(picture_params)
      #値を更新できたらredirectメソッドでindexアクションにリダイレクトさせる。
      redirect_to pictures_path, notice: "Pictureを編集しました！"
      #失敗した場合はeditアクションをrenderする。
    else
      render :edit
    end
  end
  #削除対象の値をインスタンス変数@pictureに取得。destroyメソッドを使用して、削除を実行する。
  def destroy
    #削除を実行した際に、投稿一覧に以下のメッセージを表示する。
    @picture.destroy
    redirect_to pictures_path, notice: "Pictureを削除しました！"
  end
  #バリデーションの際の条件分岐
  def confirm
    @picture = current_user.pictures.build(picture_params)
    #確認画面に移る前に、invalid?メソッドにて、バリデーションを実行させ、失敗したら投稿画面に戻す。
    render :new if @picture.invalid?
  end
  #投稿者のみ編集、削除できるようにensure_correct_userという、現在のuser_idと投稿者のidが一致していないとはじくメソッドを作成。
  def ensure_correct_user
    @picture = Picture.find_by(id: params[:id])
    #Pictureクラスからはuser_idを、Userクラスから作ったcurrent_userからはidを取得し、それが一致しない場合、indexに飛ばす。
    if @picture.user_id != current_user.id
      flash[:notice] = "権限がありません"
      redirect_to("/pictures/index")
    end
  end
  #privateメソッド配下にメソッドを記述すると、そのメソッドはPrivateMethodになり、そのクラスからしか呼び出せないようになる。
  private
  def picture_params
    #セキュリティーのために、予め受け入れるデータを文字列、画像に指定する。pictureキーの、title...のみ取得を許可する。
    params.require(:picture).permit(:title, :content, :image, :image_cache, :remove_image)
  end
  #idをキーとして値を取得するメソッドを追加
  def set_picture
    #編集する内容を入力させる。すでに存在するデータを編集して、再度保存するidを元に、データベースから当該するデータを取得。
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if  user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if current_user == @user
      if @user.update(user_params)
        flash[:success] = 'ユーザー情報を編集しました。'
        render :edit
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
      end
      else
        redirect_to "users/new"
    end
  end

  def favorites
    @user = User.find_by(id: params[:id])
    @favorites = Favorite.where(user_id: @user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.image %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image.url %>
</p>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newapplication2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <% flash.each do |key,value| %>
      <%= content_tag(:div,value,class: "#{key}")%>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id),method: :delete %>
    <% else %>
      <%= link_to "Sign up",new_user_path %>
      <%= link_to "Login",new_session_path %>
    <% end %>
    <%= yield %>
  </header>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true,url: choose_new_or_edit ) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="picture_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="picture_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="image">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url)if@picture.image&&@picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
    <p><%= form.check_box :remove_image %>画像を削除する</p>
  </div>
  <%= form.submit %>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <p>タイトル: <%= @picture.title %></p>
  <p>本文: <%= @picture.content %></p>
  <p>
    <strong>Image:</strong>
    <%= image_tag @picture.image.url if @picture.image? %>
  </p>
  <%= form.submit "登録する" %>
  <%= form.submit '戻る', name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>Pictureを編集する</h2>
<%= render 'form' %>

app/views/pictures/index.html.erb
<div class="container">
  <h1>Picture一覧</h1>
  <%= link_to '新しくPictureを投稿する', new_picture_path %></div>
  <div class="content">
    <div class="row">
      <% @pictures.each do |picture| %>
        <div class="col-md-6">
          <div class="post">
            <div class="picture_title">
              <%= link_to picture.title, picture_path(picture.id) %>
            </div>
            <div class="picture_content">
              <%= picture.content %>
              <%= link_to '詳細を確認する', picture_path(picture.id) %>
            </div>
            <div class="user_name">
              <%= picture.user.name %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<%= link_to "Picture一覧画面にもどる", pictures_path %>
<h2>Pictureを作成する</h2>
<%= render 'form' %>

app/views/pictures/show.html.erb
<%= link_to "Picture一覧画面にもどる", pictures_path %>
<h1>Picture詳細画面</h1>
<p>タイトル: <%= @picture.title %></p>
<p>内容: <%= @picture.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url if @picture.image? %>
</p>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<% if @picture.user_id == current_user.id %>
  <div class="picture-menus">
    <%= link_to "Pictureを編集する", edit_picture_path(@picture.id) %>
    <%= link_to "Pictureを削除する", picture_path(@picture.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>プロフィールを編集する</h2>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error")%>prohibited this<%= @user.name %>form being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>
<%= form_with(model: @user,local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  <%= image_tag @user.image_url if @user.image? %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/favorites.html.erb
<%= link_to "Picture一覧画面にもどる", pictures_path %>
<% @favorites.each do |favorite| %>
  <div hidden><%= picture=Picture.find_by(id: favorite.picture_id) %></div>
  <p>タイトル: <%= picture.title %></p>
  <p>本文: <%= picture.content %></p>
  <p>
    <strong>Image:</strong>
    <%= image_tag picture.image.url if picture.image? %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error")%>prohibited this<%= @user.name %>form being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>
<%= form_with(model: @user,local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  <%= image_tag @user.image_url if @user.image? %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<%= link_to "Picture一覧画面にもどる", pictures_path %>
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<p id = "notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <% if @user.image? %>
    <%= image_tag @user.image.url %>
  <% end %>
</p>
<ul class="user-tabs">
  <li><%= link_to("お気に入り", "/users/#{@user.id}/favorites") %></li>
</ul>
<%= link_to '新しくPictureを投稿する', new_picture_path %>
<%= link_to 'プロフィールを編集する', edit_user_path %>